# Generated by Django 5.1.5 on 2025-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalevent",
            name="event_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="trending_score",
            field=models.FloatField(),
        ),
    ]
