# Generated by Django 5.1.5 on 2025-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_globalevent_event_type_alter_globalevent_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalevent",
            name="event_type",
            field=models.CharField(
                choices=[("Holiday", "Holiday"), ("Weather Change", "Weather Change")],
                default="Holiday",
                max_length=255,
            ),
        ),
    ]
