# Generated by Django 5.1.5 on 2025-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_globalevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalevent",
            name="event_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
